controllers:
    resource: ../src/Controller/
    type: attribute
error_404:
    path: /{any}
    defaults:
        _controller: App\Controller\IndexController::notFound
    requirements:
        any: .*